module.exports = {
  einstein: {
    name: "Albert Einstein",
    years: "1879 - 1955",
    attrs: { Criatividade: 95, Logica: 80, Curiosidade: 90, Persistencia: 70 },
    traits: ["intuitivo", "conceitual", "questionador"],
    bio: "Albert Einstein nasceu em Ulm, Alemanha, em 1879. Considerado o fisico mais influente do seculo XX, desenvolveu a teoria da relatividade especial e geral, revolucionando a compreensao cientifica do espaco, tempo e gravidade. Emigrou para os Estados Unidos em 1933 e passou os ultimos anos de sua vida no Instituto de Estudos Avancados de Princeton.",
    discovery: "Sua equacao mais famosa, E=mc2, demonstrou que massa e energia sao intercambiaveis. Em 1921, recebeu o Nobel de Fisica pela descoberta do efeito fotoeletrico, que abriu caminho para a mecanica quantica.",
    quote: "A imaginacao e mais importante que o conhecimento. O conhecimento e limitado. A imaginacao envolve o mundo.",
    today: "Profissionais com perfil Einstein prosperam em funcoes que exigem pensamento conceitual e resolucao de problemas complexos. Sao os que propoem solucoes radicalmente diferentes e conseguem simplificar o incompreensivel em metaforas poderosas.",
    praise: "Voce e o tipo de pessoa que questiona o que todos aceitam. Enquanto a maioria aprende as regras, voce pergunta por que elas existem - e e nessa pergunta que nascem as grandes descobertas. Sua forma de pensar em imagens, em analogias, em possibilidades que ainda nao existem e um dom extraordinariamente raro. Nao subestime isso.",
    study: ["Fisica teorica e quantica", "Filosofia da ciencia", "Matematica pura", "Cosmologia e astrofisica", "Epistemologia"],
    careers: ["Pesquisador cientifico", "Professor universitario", "Consultor estrategico", "Escritor de ciencia", "Inovador em tecnologia"],
    strengths: "Voce se destaca onde o problema parece insoluvel. Quando todos desistem, voce reformula a pergunta inteira - e e ai que surgem as solucoes que ninguem havia imaginado. Em pesquisa, inovacao, ensino e estrategia, seu perfil produz resultados que poucos conseguem replicar.",
    complementary: ["Ada Lovelace", "Marie Curie"],
    desc: "Voce pensa em imagens antes de palavras. Confia na intuicao para apontar a direcao e deixa o rigor vir depois.\n- Reformula problemas inteiros em vez de resolver parte por parte\n- Cria analogias que simplificam o que parece impossivel\n- Questiona premissas que todos aceitaram como verdade",
  },
  curie: {
    name: "Marie Curie",
    years: "1867 - 1934",
    attrs: { Criatividade: 60, Logica: 95, Curiosidade: 85, Persistencia: 98 },
    traits: ["metodica", "persistente", "rigorosa"],
    bio: "Marie Curie nasceu em Varsovia, Polonia, em 1867. Foi a primeira mulher a ganhar um Premio Nobel e a unica pessoa a ganhar Nobel em duas ciencias diferentes - Fisica (1903) e Quimica (1911). Pioneira no estudo da radioatividade, trabalhou em condicoes adversas mas nunca abandonou a rigorosidade cientifica.",
    discovery: "Descobriu os elementos radio e polonio, isolando-os pela primeira vez. Seus trabalhos sobre radioatividade abriram caminho para a medicina nuclear moderna e para tratamentos de cancer com radioterapia.",
    quote: "Nada na vida deve ser temido, apenas compreendido. E hora de compreender mais para temer menos.",
    today: "Perfis com metodo Curie se destacam onde outros desistem pela complexidade. Sao os analistas que encontram o erro invisivel, os pesquisadores que nao publicam ate ter certeza.",
    praise: "Voce carrega uma forca que o mundo raramente reconhece: a capacidade de continuar quando todos ja desistiram. Nao por teimosia - mas por uma conviccao profunda de que a resposta esta ali, esperando quem tiver metodo e coragem suficientes para encontra-la.",
    study: ["Quimica analitica", "Biologia molecular", "Estatistica e probabilidade", "Medicina e farmacologia", "Fisica experimental"],
    careers: ["Pesquisadora cientifica", "Medica ou farmaceutica", "Analista de qualidade", "Epidemiologista", "Engenheira de processos"],
    strengths: "Voce se destaca onde outros perdem a paciencia. Em ambientes que exigem precisao, consistencia e tolerancia zero ao erro - medicina, pesquisa, auditoria, qualidade - seu perfil e o mais valioso que existe.",
    complementary: ["Isaac Newton", "Alan Turing"],
    desc: "Voce nao confia em achismo - refaz o teste, isola a variavel, anota tudo. Onde outros desistem, voce encontra a certeza que so o metodo traz.",
  },
  darwin: {
    name: "Charles Darwin",
    years: "1809 - 1882",
    attrs: { Criatividade: 70, Logica: 85, Curiosidade: 98, Persistencia: 90 },
    traits: ["observador", "paciente", "sistematico"],
    bio: "Charles Darwin nasceu em Shrewsbury, Inglaterra, em 1809. Naturalista e geologo, e o pai da teoria da evolucao por selecao natural. Passou cinco anos viajando pelo mundo a bordo do HMS Beagle, coletando evidencias que revolucionariam a biologia.",
    discovery: "Publicou 'A Origem das Especies' em 1859, estabelecendo a selecao natural como o mecanismo central da evolucao. Sua teoria unificou toda a biologia e ainda hoje e o fundamento de toda ciencia da vida.",
    quote: "Nao e o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta as mudancas.",
    today: "Perfis Darwin sao os estrategistas de longo prazo. Enquanto todos reagem ao imediato, eles coletam evidencias, comparam contextos e chegam a conclusoes muito mais solidas.",
    praise: "Voce tem uma das inteligencias mais raras que existem: a paciencia de esperar o padrao se revelar. Enquanto outros agem com pressa, voce observa, coleta, compara - e chega a conclusoes que resistem ao tempo.",
    study: ["Biologia evolutiva", "Antropologia cultural", "Geologia e paleontologia", "Analise de dados", "Sociologia e comportamento"],
    careers: ["Biologo ou zoologo", "Analista de tendencias", "Pesquisador de mercado", "Jornalista investigativo", "Estrategista de produto"],
    strengths: "Voce se destaca em projetos de longo prazo que exigem paciencia estrategica rara. Em analise de dados, pesquisa e estrategia, voce produz insights que outros simplesmente nao enxergam.",
    complementary: ["Albert Einstein", "Ada Lovelace"],
    desc: "Voce observa antes de concluir. Coleta, compara, aguarda - e quando fala, tem evidencias que ninguem mais percebeu.",
  },
  davinci: {
    name: "Leonardo da Vinci",
    years: "1452 - 1519",
    attrs: { Criatividade: 99, Logica: 80, Curiosidade: 99, Persistencia: 75 },
    traits: ["multidisciplinar", "criativo", "visionario"],
    bio: "Leonardo da Vinci nasceu em Vinci, Italia, em 1452. Pintor, escultor, arquiteto, musico, matematico, engenheiro e anatomista - e considerado o maior genio polimata da historia. Seus cadernos revelam conceitos que anteciparam inventos do seculo XX.",
    discovery: "Pintou a Mona Lisa e A Ultima Ceia, obras que definiram o Renascimento. Projetou maquinas voadoras, tanques de guerra, energia solar e calculadoras - seculos antes de qualquer uma ser construida.",
    quote: "A simplicidade e a sofisticacao maxima.",
    today: "Em um mundo de superespecialistas, o perfil Da Vinci e o unico que enxerga a paisagem inteira - e e justamente ai que surgem as solucoes mais elegantes.",
    praise: "Voce e o elo entre mundos que nunca se encontram. Sua curiosidade sem limites nao e distracao: e exatamente o que te torna insubstituivel. Em um mundo que fragmenta o conhecimento, voce reconecta tudo.",
    study: ["Design e arquitetura", "Engenharia e prototipagem", "Historia da arte", "Anatomia e medicina", "Musica e matematica"],
    careers: ["Designer criativo", "Empreendedor", "Diretor de inovacao", "Arquiteto", "Criador de conteudo multidisciplinar"],
    strengths: "Voce se destaca em funcoes que exigem sintese criativa entre areas diferentes. Onde outros precisam de um time inteiro de especialistas, voce conecta tudo sozinho.",
    complementary: ["Nikola Tesla", "Albert Einstein"],
    desc: "Voce nao se especializa - voce conecta. Arte, ciencia, tecnologia: tudo e territorio seu. E nessa intersecao que suas melhores ideias nascem.",
  },
  turing: {
    name: "Alan Turing",
    years: "1912 - 1954",
    attrs: { Criatividade: 85, Logica: 99, Curiosidade: 88, Persistencia: 85 },
    traits: ["logico", "sistematico", "preciso"],
    bio: "Alan Turing nasceu em Londres em 1912. Matematico e pioneiro da ciencia da computacao, quebrou o codigo Enigma dos nazistas durante a Segunda Guerra Mundial, salvando milhoes de vidas. E considerado o pai da computacao moderna e da inteligencia artificial.",
    discovery: "Criou a Maquina de Turing, fundamento teorico de todos os computadores modernos. Desenvolveu o Teste de Turing, primeiro criterio cientifico para avaliar inteligencia em maquinas.",
    quote: "Maquinas que pensam nao sao diferentes de mentes que calculam.",
    today: "Perfis Turing constroem sistemas que funcionam com ou sem eles. Sao os que criam processos claros, escalasveis e livres de ambiguidade.",
    praise: "Voce tem um superpoder raramente reconhecido: transformar o caotico em sistematico. Onde outros veem confusao, voce ve padroes. Onde outros improvisam, voce cria regras que funcionam para sempre.",
    study: ["Ciencia da computacao", "Matematica discreta", "Logica e teoria da computacao", "Criptografia", "Inteligencia artificial"],
    careers: ["Desenvolvedor de software", "Engenheiro de dados", "Arquiteto de sistemas", "Especialista em IA", "Analista de seguranca digital"],
    strengths: "Voce se destaca em construir sistemas que funcionam com ou sem voce. Em equipes e empresas que precisam de processos claros e escalaveis - seu perfil e insubstituivel.",
    complementary: ["Marie Curie", "Ada Lovelace"],
    desc: "Voce pensa em sistemas. Cada problema e um algoritmo esperando para ser descoberto - e voce tem a paciencia e a logica para encontra-lo.",
  },
  lovelace: {
    name: "Ada Lovelace",
    years: "1815 - 1852",
    attrs: { Criatividade: 90, Logica: 95, Curiosidade: 92, Persistencia: 80 },
    traits: ["analitica", "visionaria", "pioneira"],
    bio: "Ada Lovelace nasceu em Londres em 1815, filha do poeta Lord Byron. Matematica e escritora, e considerada a primeira programadora da historia - um seculo antes dos computadores existirem. Trabalhou com Charles Babbage na Maquina Analitica.",
    discovery: "Escreveu o primeiro algoritmo destinado a ser processado por uma maquina. Mais importante: foi a primeira a perceber que maquinas poderiam fazer muito mais do que calcular - poderiam criar.",
    quote: "A imaginacao e a faculdade descobridora por excelencia.",
    today: "Perfis Lovelace lideram projetos que ainda nao existem. Sao os que enxergam o potencial de uma ideia antes de qualquer outra pessoa e articulam esse futuro com precisao suficiente para inspirar outros.",
    praise: "Voce combina duas forcas que raramente convivem no mesmo cerebro: rigor analitico e imaginacao estrategica. A maioria tem um ou outro. Voce tem os dois - e isso coloca voce decadas a frente do que qualquer especialista consegue ver.",
    study: ["Programacao e algoritmos", "Matematica aplicada", "Filosofia da tecnologia", "Design de sistemas", "Empreendedorismo tecnologico"],
    careers: ["Product manager", "CTO ou lider tecnica", "Engenheira de software", "Estrategista de inovacao", "Fundadora de startup"],
    strengths: "Voce se destaca ao liderar projetos que ainda nao existem. Sua capacidade de ver o potencial de uma ideia antes de qualquer outra pessoa e articular esse futuro com precisao e o que separa os que constroem o amanha dos que apenas o observam.",
    complementary: ["Albert Einstein", "Nikola Tesla"],
    desc: "Voce enxerga o futuro antes dos outros. Nao e intuicao - e a combinacao rara de logica precisa com imaginacao sem limites.",
  },
  tesla: {
    name: "Nikola Tesla",
    years: "1856 - 1943",
    attrs: { Criatividade: 95, Logica: 90, Curiosidade: 85, Persistencia: 92 },
    traits: ["visionario", "obsessivo", "inovador"],
    bio: "Nikola Tesla nasceu na Serbia em 1856. Inventor e engenheiro eletrico, desenvolveu o sistema de corrente alternada (CA) que alimenta o mundo ate hoje. Registrou mais de 300 patentes e imaginou tecnologias que so se tornaram realidade decadas depois de sua morte.",
    discovery: "Inventou o motor de inducao e o sistema de transmissao de energia em corrente alternada - a base de toda a eletricidade moderna. Previu o Wi-Fi, drones e a internet com decadas de antecedencia.",
    quote: "O presente e deles; o futuro, pelo qual trabalhei, e meu.",
    today: "Perfis Tesla se destacam em inovacao disruptiva. Sao os que simulam sistemas complexos inteiramente na mente antes de executar - e chegam a solucoes que ninguem havia imaginado.",
    praise: "Voce vive no futuro. Enquanto outros ainda discutem o que e possivel, voce ja esta construindo mentalmente - em detalhes, com clareza - coisas que o mundo levara decadas para entender. Isso nao e loucura: e visao.",
    study: ["Engenharia eletrica e eletronica", "Fisica aplicada", "Energia e sustentabilidade", "Robotica e automacao", "Filosofia da ciencia"],
    careers: ["Engenheiro de inovacao", "Inventor e patentista", "Fundador de startup tecnologica", "Pesquisador de energia", "Especialista em sistemas eletricos"],
    strengths: "Voce se destaca em projetos que exigem obssao criativa e visao de longo prazo. Sua capacidade de simular sistemas complexos inteiramente na mente antes de executa-los e um diferencial extraordinario.",
    complementary: ["Leonardo da Vinci", "Ada Lovelace"],
    desc: "Voce constroi na mente antes das maos. O projeto esta completo na sua cabeca muito antes de qualquer ferramenta ser tocada.",
  },
  oppenheimer: {
    name: "J. Robert Oppenheimer",
    years: "1904 - 1967",
    attrs: { Criatividade: 85, Logica: 95, Curiosidade: 88, Persistencia: 90 },
    traits: ["lider", "estrategico", "profundo"],
    bio: "J. Robert Oppenheimer nasceu em Nova York em 1904. Fisico teorico e diretor cientifico do Projeto Manhattan, liderou a equipe que desenvolveu as primeiras bombas atomicas. Era fluente em oito idiomas e conhecido por reunir as maiores mentes da ciencia em torno de um objetivo.",
    discovery: "Liderou o desenvolvimento da bomba atomica em Los Alamos durante a Segunda Guerra Mundial. Mais tarde, tornou-se um dos maiores criticos da proliferacao nuclear - carregando o peso etico de sua propria criacao.",
    quote: "Agora me tornei a Morte, o destruidor de mundos.",
    today: "Perfis Oppenheimer lideram em alta pressao onde as consequencias sao grandes. Sao os diretores que coordenam mentes excepcionais, tomam decisoes sob pressao e carregam o peso etico das proprias escolhas.",
    praise: "Voce tem o que os maiores lideres levam uma vida inteira para desenvolver: a capacidade de reunir mentes excepcionais em torno de um objetivo, sustentar a complexidade de um projeto enorme sem perder profundidade individual, e carregar o peso das consequencias com consciencia plena.",
    study: ["Fisica teorica", "Filosofia e etica aplicada", "Gestao e lideranca", "Politica e relacoes internacionais", "Literatura e humanidades"],
    careers: ["Diretor cientifico", "Gestor de projetos complexos", "Consultor estrategico senior", "Lideranca executiva", "Politico ou diplomata"],
    strengths: "Voce se destaca em lideranca de alto nivel onde a pressao e extrema e as consequencias sao grandes. Quando voce entra numa sala, o nivel sobe.",
    complementary: ["Marie Curie", "Alan Turing"],
    desc: "Voce lidera o que ninguem mais consegue segurar. Projetos grandes, times excepcionais, decisoes pesadas - esse e o seu territorio.",
  },
  newton: {
    name: "Isaac Newton",
    years: "1643 - 1727",
    attrs: { Criatividade: 80, Logica: 99, Curiosidade: 90, Persistencia: 98 },
    traits: ["metodico", "profundo", "fundacional"],
    bio: "Isaac Newton nasceu em Woolsthorpe, Inglaterra, em 1643. Matematico, fisico, astronomo e filosofo natural, e amplamente considerado o maior cientista de todos os tempos. Desenvolveu o calculo diferencial e integral simultaneamente ao matematico Leibniz.",
    discovery: "Formulou as tres leis do movimento e a lei da gravitacao universal. Inventou o calculo. Descobriu que a luz branca e composta de todas as cores do espectro. Cada uma dessas contribuicoes sozinha ja seria suficiente para uma vida de genio.",
    quote: "Se enxerguei mais longe, foi por estar sobre ombros de gigantes.",
    today: "Perfis Newton constroem do zero. Quando as ferramentas existentes nao resolvem o que enfrentam, eles criam novas - e essas ferramentas tornam-se a base que outros usam por geracoes.",
    praise: "Voce nao aceita respostas pela metade. Quando algo nao esta explicado ate o fundo, voce continua - e continua - ate ter um sistema completo. Essa recusa em se contentar com 'bom o suficiente' e o que separa os que descobrem leis dos que apenas as aplicam.",
    study: ["Matematica pura e calculo", "Fisica classica e quantica", "Filosofia natural e epistemologia", "Astronomia", "Engenharia fundamental"],
    careers: ["Matematico teorico", "Fisico de pesquisa fundamental", "Engenheiro senior", "Professor universitario", "Especialista em analise quantitativa"],
    strengths: "Voce se destaca em construir do zero. Em matematica, fisica, engenharia e qualquer area que exija pensar a partir de principios primeiros, seu perfil e fundacional.",
    complementary: ["Marie Curie", "Albert Einstein"],
    desc: "Voce nao para enquanto nao entende tudo. Cada lei, cada principio - voce precisa derivar do zero para realmente confiar.",
  },
};
